name: Spring API CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Get pubspec version
        run: |
          export VERSION=$(grep 'version = ' build.gradle | cut -f 2 -d "'")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Java 11
        uses: openjdk/11-jre-slim-stretch
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/anlix-api:latest
            docker.pkg.github.com/${{ github.repository }}/anlix-api:${{ env.VERSION }}